### ISSUE TITLE
FEATURE Request - Tip me if you like these and can make under 20 minutes

### ISSUE THREAD

**Issue by RadientBrain** [VulcanWM/melody-maker#10]
1) Tempo Adjustment

A slider or similar interface that allows users to adjust the tempo of the generated melody. This feature would allow users to generate melodies that fit within a specific tempo range.

2) Melody Length Option

An input field that allows users to specify the length of the melody in terms of bars or beats. This feature would allow users to generate melodies of a specific length.

3) Rhythm Pattern Selection

A dropdown menu or similar interface that allows users to select a rhythm pattern for the melody. This feature would allow users to generate melodies with specific rhythmic characteristics.

4) Instrument Selection

A dropdown menu or similar interface that allows users to select the instrument sound for the generated melody. This feature would allow users to hear the melody as it might sound on different instruments.

**Comment by VulcanWM** [comment]
the second one seems the easiest to implement, ill work on that!

**Comment by VulcanWM** [comment]
implemented the melody length option, enjoy the tip!

**Comment by RadientBrain** [comment]
Thats great! Thank you for the tip :)
