### ISSUE TITLE
Melody Playing On top each other.

### ISSUE THREAD

**Issue by boredmage** [VulcanWM/melody-maker#6]
Clicking on Play melody buttons keeps playing the same melody over and over again without stopping the intial play and this cause a nuisance I think.

To simulate this, select a tonality of your choice and keep pressing play melody as many times as you want and you can see same melody playing on top each other.

**Comment by sonicx180** [comment]
Nice catch!

**Comment by VulcanWM** [comment]
oh yea I forgot about that, i'll work on fixing that!
meanwhile enjoy your 1k cycles tip!

**Comment by boredmage** [comment]
Thanks
