### ISSUE TITLE
Verifying Sharing URL

### ISSUE THREAD

**Issue by boredmage** [VulcanWM/melody-maker#7]
You set [var melodyExists = false;](https://github.com/VulcanWM/melody-maker/blob/01acd5ae129197df2c22ec08a74cd52f5ec08d4c/pages/share.js#L13), while the page is loading before the share link is verified, [Incorrect sharing url!](https://github.com/VulcanWM/melody-maker/blob/01acd5ae129197df2c22ec08a74cd52f5ec08d4c/pages/share.js#L228C37-L228C59) is rendered and within a twinkle of an eye, it dissapears and the melody shows up. 

I would rather suggest to have a preloader that spins to show a status of loading prior to when the link is resolved or rejected, so in that case, you can show either *Incorrect sharing url!* or the melody to play.

**Comment by VulcanWM** [comment]
yea I've decided to use serverside rendering for that, nice catch though!
