### ISSUE TITLE
Button for stop playing the melody

### ISSUE THREAD

**Issue by f4rukyldrm** [VulcanWM/melody-maker#9]
I think being able to stop and continute to play the melody would be good. And If you add this feature on top of play button you would solve the issue 6.

**Comment by VulcanWM** [comment]
yea this will probably fix #6 and #9

**Comment by VulcanWM** [comment]
added this!
thanks for the suggestion and enjoy the 1k cycles!

**Comment by VulcanWM** [comment]
adding this also meant that it fixed #8 and also fixed #6

**Comment by f4rukyldrm** [comment]
Thanks
